=== Xuxueli6/Xml_Learning/Library.dtd
<!DOCTYPE Library
[
<!ELEMENT Library (Book,Member)>
<!ELEMENT Book (title,Author,Publisher,Cost)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT Cost (#PCDATA)>
<!ELEMENT Member (Name,Address)>
<!ELEMENT Name (FirstName,MiddleName,LastName)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Address (HouseNumber,Street,City)>
<!ELEMENT HouseNumber (#PCDATA)>
<!ELEMENT City (#PCDATA)>
]>

=== Xuxueli6/Xml_Learning/xml验证文件.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Library SYSTEM "Library.dtd">
<Library>
	<Book>BookId
		<title></title>
		<Author></Author>
		<Publisher></Publisher>
		<Cost></Cost>
	</Book>
	<Memeber>
		<Name>
			<FirstName></FirstName>
			<MiddleName></MiddleName>
			<LastName></LastName>
		</Name>
		<Address>
			<HouseNumber></HouseNumber>
			<Street></Street>
			<City></City>
		</Address>
	</Memeber>
</Library>
